language: node_js
node_js:
- 8
deploy:
  provider: firebase
  token:
    secure: KjgqCEYEhUDtjhuBeeWlGnxLPk9aOke2o+sXRkr4w8WvLCurR3zXYelBtSNM1ICBVGSPwhTuRrkmD3RTjTe3pbyHacgxgkhWL1H3YZcWQcruEoChWJPwlJgvfAR4Poy7O4lVWaS6nEkgMvnNKjHBXJSvjB0jsHylv45JetLxOIPFoLlyiYMhUoZ3oylrIvFV4Cgcp2EV9IdA8NTl125+1a/pJoifpKhjI949kiQ23dEOi40cNSHSQ+gU8d+/HWIC2xQmKUg6J+woTN2higSeqzHwCkXld8KxAhx2dHleoaOyluyEnCT+VoJv5hHW6tgCpwD374e7hszPTwwXAkNySJTGLjejEzD7Hsg6NCv4ty+R3NH5upEChJlgdVK4s8H0fIicg6qWoDP5kR5X8gIoS/ODqOOZRA/v4rVs2shRaLouLpv+UNejHyO/Jcghsd847U8hI0Y9EFwrWKXgc3gyPIG56zi3qto1l2G3ndTMOlMXfV/HVfAmGupor3q2poP6RRoYSt9rculAgBNIpyRsLygpAZIA5/XqxKJUYbCOqZtCzm6n6xwKPSEAp6WdsI0GkPodHt1xlxl+2//WdWLZ0/OAJv1B4t4ge7Q2nbciP/3JF2gLvBvjBBnl0jwRviYZWW1L6IvbN9Tm7xNxjkPwRmPgskIoLHHaMJzweWXEaGo=
  project: hello-6d31f