language: node_js
node_js:
- 8
deploy:
  provider: firebase
  token:
    secure: "OLdlNVTbqT4gnIAcjBG7g+PH0I/h8l9ndat5KWYHQOGmlzK+Ohnf58tPHMTv74CfucL0MyRl0GPWZD43Xq7SpV7ZvWWf+kQsdQ6m+5vJCfZEmpPX40D4Rn2p9GbWHEx1m1b7MwwFbUlSJnyyn/fSTrharQbSAuGISymXmFOfOeKYZIDDLa4JK3V7wKPgVhbfNhKwPk5xbE9zb6fjihASBnltzLPV2L20ZsapK1ci9DaVjyyo/wtiFJJNn3r4Jf6rwFyROnTDkvCUAAWou2YySf5z/3U/vuCwVvUg5ZLNr8Z5/EtRxPeaC4GrTAmCYi8B3zrJBh+sYC3Rf4ZvAuoISPNLPBVSaaugKushxuZM5sk5wp3thVv4GkQQC63m31yBstDZ/x1ZjZZfQrsDn7K0hs5fAdRPYZNyCvw/Sq1nHTfpwWZaZ3tfPuviMHO1pbf99TE6IF9oyhh+QtPhzWNBHRuCWxcE5fsPrbiBe8ESEasLbWUKy67ywyDPlykpAdbKvn7doPAREWnst4kX4L1relWkuD3IfqMgbShfj5k7HXtldIuVVTFHikqkdtfqcQ59o5N36XRhyqEAHoH1MK4lmXCJ6cr0X3HXV29QcHT5Q69d56s+IyL8ozVi9WCb2Kt2IvAmMs0CWp+HbgjP7KXv6wQDSAlJTf4rQLKcTFXn1xo="
  project: hello-6d31f