language: node_js
node_js:
  - 8
install:
  - npm install -g firebase-tools
  - npm install
script:
  - webpack
  - cd dist
  - git add .
deploy:
  provider: firebase
  token:
    secure: "1/IMxhVNXJNiSg9tEKKkp01H4mbWzvC5CQLhzvPHpM9y0"
  project: "hello-6d31f"
  skip_cleanup: true