language: node_js
node_js:
  - "node"
install:
  - npm install -g firebase-tools
  - npm install
script:
  - webpack --config webpack.config.js
skip_cleanup: true
deploy:
  provider: firebase
  token:
    secure: "1/IMxhVNXJNiSg9tEKKkp01H4mbWzvC5CQLhzvPHpM9y0"
  project: "hello-6d31f"