language: node_js
node_js:
  - "node"
before_install:
  - npm install -g firebase-tool
install:
  - npm install
  - npm run build
  - npm run deploy
script:
  -
deploy:
  provider: firebase
  token:
    secure: "1/IMxhVNXJNiSg9tEKKkp01H4mbWzvC5CQLhzvPHpM9y0"
  project: "hello-6d31f"