language: node_js
node_js:
  - 8
cache:
  directories:
    - node_modules
script:
  - cd dist 
  - npm install
  - cd ..
deploy:
  provider: firebase
  token:
    secure: "1/IMxhVNXJNiSg9tEKKkp01H4mbWzvC5CQLhzvPHpM9y0"
  project: "hello-6d31f"