language: node_js
node_js:
- 8
deploy:
  provider: firebase
  token:
    secure: "rbA/N6QagjVYkuAAQr5sNoMym1vkxULaGD8s8f/OzVoJoNdnH1U0mrOKPb9kNOKI87Qtm4yt/PY5hJS9cbKUaOfvdvYvIV6MJ4+6pyFSdroky0Tg0/Uep2Cj33w5O1osY/VwsnteMuK1QFLO8luRa1YHOGpL5PbbYrRNSu7rN6mVGBzaPOlm+vQD/FNIOTMSGqhN0vfi98F3RZ4uYaEUZri3gUVi1LllZUV+ah21OBfNlms4UN1kTT5pwqsF/8VPcih3pGG6dWCPRPEyyVoH33T1wHNDvJbfSCcFARah0iG3saks+o4/6clA7LIqbTjr95OUojbmzeLLgUReQxyCSetZRHMzZ66v5dEQok8zJTNN0zd5dxet6xzLl+T7QdnoPnHkbCiiex5UyMiFgi+WQ11aPgqsQlQxNMlyhO4UMn1ALnXSUwq4hmAZt15M7olrmm+2KhtlN1vKK/Lju4szANOjhtKPxsoKLK6A4XbM/FgKQQFw2vWCiL4P2wcDDx0hp4/RvFZ0BzIuQbv6XYPi3vkQErNRlk6YDx8forE8lzaTR757nkpYL55M/7fjhtOvf8Chso8d3Q3tOcVEOvTK2vnmw/jxXzM6UZVHlMLcO6XI0CC71v5R8Cq08FhorAjCsEpVDABcwyIsdrpbF7jbRUurS4E4EzY8ZhA+QGu9aLU="
  project: hello-6d31f