language: node_js
node_js:
  - 8
cache:
  directories:
    - node_modules
install:
  - npm install -g firebase-tools
  - npm install
deploy:
  provider: firebase
  token:
    secure: "1/IMxhVNXJNiSg9tEKKkp01H4mbWzvC5CQLhzvPHpM9y0"
  project: "hello-6d31f"